#!/bin/sh
;--------;
; COLORS ;
;--------;
[colors]
background-alt = #444
foreground-charging = #ffd61a
#primary = #7e9cd8
secondary = #e60053
alert = #bd2c40
#background = #1f1f28
background-urgent = #c34043
#foreground = #xdcd7ba
border-color = 0

;-------------------------
; Catppuccin Mocha Palette
; Maintainer: justTOBBI
;--------------------------

[colors]
background = #1e1e2e
mantle = #181825
crust = #11111b

foreground = #cdd6f4
primary = #89b4fa

subtext0 = #a6adc8
subtext1 = #bac2de

surface0 = #313244
surface1 = #45475a
surface2 = #585b70

overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2


blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc

transparent = #FF00000




[bar/mainBar]

;------------;
; DIMENSIONS ;
;------------;

foreground = ${colors.foreground}
background = ${colors.background}
width = 100%
height = 26
offset-y = 0
offset-x = 0
radius = 2

border-top-size = 1
border-bottom-size = 1
border-right-size = 1
border-left-size = 0

;----------;
; LOCATION ;
;----------;

bottom = false
monitor = ${env:MONITOR:}
;monitor = DP1-2
;override-redirect = false

;-------;
; FONTS ;
;-------;

font-0 = Hack:size=10;3
font-1 = "Font Awesome 6 Free:style=Solid:pixelsize=12;3"
font-2 = "Font Awesome 6 Free:style=Regular:pixelsize=12;3"
font-3 = "Font Awesome 6 Brands:pixelsize=12;3"
font-4 = Hack:size=10:weight=bold;2



;---------------;
; MISCELLANEOUS ;
;---------------;

fixed-center = true
padding-left = 0
padding-right = 2
module-margin = 1.5

modules-left = i3
modules-center = date time spotify previous playpause next 
modules-right = wlan xkeyboard cpu memory temperature volume battery

tray-position = right
tray-padding = 0
enable-ipc = true


;---------;
; MODULES ;
;---------;

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false
format-padding = 0
label-unfocused-font = 5
label-focused-font = 5
; Only show workspaces on the same output as the bar
pin-workspaces = true

label-mode-padding = 1
label-mode-foreground = ${colors.foreground}
label-mode-background = ${colors.primary}

; focused = Active workspace on focused monitor
label-focused = %index%
label-focused-background = ${colors.primary}
label-focused-foreground = ${colors.background}
label-focused-underline = ${colors.primary}
label-focused-padding = 1

; unfocused = Inactive workspace on any monitor
label-unfocused = %index%
label-unfocused-padding = 1

; visible = Active workspace on unfocused monitor
label-visible = %index%
label-visible-background = ${colors.background-alt}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = 1

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.background-urgent}
label-urgent-padding = 1

[module/time]
type = internal/date

interval = 1.0

date =  %H:%M

[module/date]
type = internal/date
date = %e %B - %A
label = %date%


[module/battery]
type = internal/battery

battery = BAT1

poll-interval = 1

full-at = 95

label-discharging = %percentage%%
label-charging = %percentage%%
label-full = %percentage%%

format-discharging = <ramp-capacity> <label-discharging>
format-full = <ramp-capacity> <label-full>
format-charging =  <label-charging>

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

[module/volume]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>
format-muted =  0%

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 


[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true

format = <ramp> <label>

label = %percentage%%

ramp-0 = 
ramp-1 = 
ramp-2 = 

[module/wlan]
type = internal/network

interface = wlp2s0

interval = 5

label-connected =  %essid%
label-disconnected =  Not Connected

[module/cpu]
type = internal/cpu
label =  %percentage:02%%


[module/memory]
type = internal/memory
label =  %percentage_used%%

[module/network]
type = internal/network
interface = wlp2s0
label-connected =  %downspeed% |  %upspeed%



[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60

format = <ramp> <label>
;format-underline = #f50a4d
format-warn = <ramp> <label-warn>
;format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}

ramp-0 = 
ramp-1 = 
ramp-2 = 
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input

[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
blacklist-1 = scroll lock

layout-icon-0 = us
layout-icon-1 = lt

format-prefix = " "
format-prefix-foreground = ${colors.foreground}
format-prefix-underline = ${colors.secondary}

[module/previous]
type = custom/ipc
; Default
hook-0 = echo ""
; When spotify active
hook-1 = echo ""
click-left = "spotifyctl -q previous"


[module/next]
type = custom/ipc
; Default
hook-0 = echo ""
; When spotify active
hook-1 = echo ""
click-left = "spotifyctl -q next"


[module/playpause]
type = custom/ipc
; Default
hook-0 = echo ""
; Playing
hook-1 = echo ""
; Paused
hook-2 = echo ""
click-left = "spotifyctl -q playpause"


[module/spotify]
label-padding-left=4
type = custom/ipc
; Default
hook-0 = echo ""
; Playing/paused show song name and artist
hook-1 = spotifyctl -q status --format '%artist%: %title%'
